#!/bin/bash
set -eux

# portage設定ファイルをデバイスの環境に合わせて生成する。

# スクリプトのディレクトリ位置を保持する。
script_dir=$(dirname "$0")

# `MAKEOPTS`でジョブ数をCPUコア数にするのは動的な処理が必要。
install-make-conf() {
  cp "$script_dir"/install.d/make.conf.base "$script_dir"/make.conf

  echo "
## makeopts

MAKEOPTS='-j$(nproc)'" >> "$script_dir"/make.conf
}

# AVXなどの使えるCPUの使える機能を読み出すにはコマンド呼び出しが必要。
install-cpu-flags() {
  echo "*/* $(cpuid2cpuflags)" > "$script_dir"/package.use/install-cpu-flags
}

# デバイスによって搭載されているビデオカードが異なる。
install-video() {
  case $(hostname) in
    bullet)
      # AMD GPU + NVIDIA GPU構成ですが、AMDのCPU内蔵GPUは使わない。
      video_card=nvidia
      ;;
    creep)
      # AMD GPUのみ。
      video_card=amd
      ;;
    *)
      echo "Unknown hostname: $(hostname)" >&2
      exit 1
      ;;
  esac
  case $video_card in
    nvidia)
      echo '*/* VIDEO_CARDS: -* nvidia' > "$script_dir"/package.use/install-video-cards
      echo '*/* vdpau nvdec nvenc' > "$script_dir"/package.use/install-video-acceleration
      ;;
    amd)
      echo '*/* VIDEO_CARDS: -* amdgpu radeonsi' > "$script_dir"/package.use/install-video-cards
      # amfは現状プロプライエタリなドライバが必要らしいのと、
      # 現状AMD GPUで動画をエンコードする需要が個人的に無いので有効化していない。
      echo '*/* vaapi vdpau' > "$script_dir"/package.use/install-video-acceleration
      ;;
    *)
      echo "Unknown video card: $video_card" >&2
      exit 1
      ;;
  esac
}

install-make-conf
install-cpu-flags
install-video
